### ISSUE TITLE
Error in login_check

### ISSUE THREAD

**Issue by PSF1** [yivi/YivoffJwtRefreshBundle#3]
Hi,

When I call to refresh the token I get the "The key 'username' must be provided.". If I add the 'username' key to the payload I get "The key 'password' must be provided.".

Is possible that I need any configuration to overwrite the login_check controller?

My environment:
- Symfony: 5.4
- API Platform: 2.6.7
- Doctrine: 2.10.4
- jwt-refresh-bundle: 1.0.0
- jwt-authentication-bundle: 2.14.3

In security.yaml, key security.firewalls.login I have:
```yaml
        login:
            pattern: /api/v1/users/login
            stateless: true
            methods: [POST]
            provider: user_provider
            custom_authenticators:
                - yivoff_jwt_refresh.authenticator
            json_login:
                check_path: /api/v1/users/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
```

Note that in custom_authenticator I used the service alias because the class name doesn't work. It may be a documentation mistake.

My bundle configuration:

```yaml
# config/packages/jwt-refresh-bundle.yaml
yivoff_jwt_refresh:
  token_provider_service: 'App\Security\Core\user\RefreshTokenProvider'
  token_ttl: '%env(JWT_REFRESH_TOKEN_TTL)%'
  parameter_name: 'refresh_token'
```

`JWT_REFRESH_TOKEN_TTL` is 1800.

**Comment by yivi** [comment]
Hi Pedro. 

How are you calling the refresh endpoint? Could you please provide the request? 

Considerig your configuration it should be something like:

```http
POST http://localhost:7099//api/v1/users/login
Content-Type: application/x-www-form-urlencoded

refresh_token=token_identifier:token_key
```

Note the content-type: it needs to go as `application/x-www-form-urlencoded`.

**Comment by PSF1** [comment]
First I call to get the access token with:
```bash
curl -X 'POST' \
  'http://example.localhost/api/v1/users/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "generatedPassword"
}'
```

And I get:
```json
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDMwMDkyNjUsImV4cCI6MTY0MzAxMDE2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IkFkbWluIiwiaXAiOiIxNzIuMTguMC4zIiwiaWQiOiIwMUZTWFdBRE1YUUVCUlJGV1c1Qkc4RlZERCJ9.DWHL4ksTOVMfIZrpH9MVyymqtueLNBWMhDY1qYnld_SnWEd7kfy_H0eogPlLirtoIT2_vZyQgFFhOKx0huXWS6V_bsMXU0OUhGNp3wh8l4PMDNHEcydwSMYBf1BnpUZXXx7qim34uL4Blb-RU-OdkuH7PihG2vC2XD51zuT29r9OrUVuv-WKxWQ25jv-adKIGOgS9tamRXGkkzO6FIlvzOhoEUTCxLcbSj_Zg17FmTpNKnfjeNiWLQqrHnrA3dT5XO-FFFeBFsCNdTSsrMPEoUGHsLZ-sCvdYDB8pRZnOfZ8xjrnWGDYI3paUTZXxqOKvHMsS6acwv4UTopQVizgUg",
  "refresh_token": "k0wc79ivsx4l4t9r2ph5:ot9wfkk6f2f706pams1m9dc8wut10wko"
}
```

Then to refresh the access token:
```bash
curl -X 'POST' \
  'http://example.localhost/api/v1/users/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "refresh_token": "k0wc79ivsx4l4t9r2ph5:ot9wfkk6f2f706pams1m9dc8wut10wko"
}'
```

And I get:
```json
{
  "class": "Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException",
  "code": 400,
  "message": "The key \"username\" must be provided."
}
```

I use Swagger UI, it's integrated with the API Platform, and always uses `application/json` how content-type.

If I change the call to use `x-www-form-urlencoded`:
```bash
curl --location --request POST 'http://example.localhost/api/v1/users/login' \
--header 'accept: application/json' \
--header 'accept: application/x-www-form-urlencoded' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'refresh_token=k0wc79ivsx4l4t9r2ph5:ot9wfkk6f2f706pams1m9dc8wut10wko'
```

I get:
```json
{
    "error": "Bad credentials."
}
```

I thought that the refresh endpoints is an overwrite of the login endpoint, at the code level. Is it another route?

How can I debug it?

thx so much :)

**Comment by yivi** [comment]
Hello again Pedro. 

The call to the refresh token needs to be using `Content-Type: application/x-www-form-urlencoded`. You are sending it using `Content-type: application/json`. Check how I send the request in my [previous comment](https://github.com/yivi/YivoffJwtRefreshBundle/issues/3#issuecomment-1019295077).

It's the same route, but while the login request is `aplication/json`, the refresh request uses  `application/x-www-form-urlencoded` (so the payload should be encoded accordingly).

Currently this does not support receiving the request using `application/json`, I'll see about adding support maybe later on the week, but I haven't needed it so far.

**Comment by PSF1** [comment]
Thanks Ivan,

I think that may be interesting to get compatibility with API Platform, https://api-platform.com/ .

To have this bundle working with it, I needed to implement a new refresh token authenticator this way:

```yaml
# config/services.yaml

    # Refresh token provider alias.
    app.refresh_token_provider:
        class: App\Security\Core\user\RefreshTokenProvider
        lazy: true
        public: true

    # Refresh token JSON authenticator.
    app.refresh_token_authenticator:
        class: App\Security\Core\user\RefreshTokenAuthenticator
        lazy: true
        public: true

    # Refresh token provider interface alias.
    Yivoff\JwtRefreshBundle\Contracts\RefreshTokenProviderInterface:
        alias: 'App\Security\Core\user\RefreshTokenProvider'
```

```yaml
# config/packages/security.yaml
...
         custom_authenticators:
                - app.refresh_token_authenticator
...
```

The authenticator is a copy of your code, but with a few changes to understand JSON payload:
```php
<?PHP

// src/Security/Core/user/RefreshTokenAuthenticator.php

declare(strict_types=1);

namespace App\Security\Core\user;

use App\Tools\Json;
use Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler;
use Symfony\Component\HttpFoundation;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\SelfValidatingPassport;
use Yivoff\JwtRefreshBundle\Contracts\HasherInterface;
use Yivoff\JwtRefreshBundle\Contracts\RefreshTokenInterface;
use Yivoff\JwtRefreshBundle\Contracts\RefreshTokenProviderInterface;
use function explode;
use function str_contains;
use function time;

class RefreshTokenAuthenticator extends AbstractAuthenticator
{
    protected string $parameterName;

    public function __construct(
        private HasherInterface $encoder,
        private AuthenticationSuccessHandler $successHandler,
        private RefreshTokenProviderInterface $tokenProvider
    ) {
        $this->parameterName = 'refresh_token';
    }

    public function authenticate(HttpFoundation\Request $request): PassportInterface
    {
        // JSON compatibility.
        $body = Json::decode($request->getContent());
        $credentials = (string) $body[$this->parameterName];

        if (!str_contains($credentials, ':')) {
            throw new AuthenticationException('Invalid Token Format');
        }

        [$tokenId, $userProvidedVerification] = explode(':', $credentials);

        $token = $this->tokenProvider->getTokenWithIdentifier($tokenId);

        if (!$token instanceof RefreshTokenInterface) {
            throw new AuthenticationException('Token Does Not Exist');
        }

        if ($token->getValidUntil() <= time()) {
            throw new AuthenticationException('Token expired');
        }

        if (!$this->encoder->verify($userProvidedVerification, $token->getVerifier())) {
            throw new AuthenticationException('Token verification failed');
        }

        return new SelfValidatingPassport(new UserBadge($token->getUsername()));
    }

    public function supports(HttpFoundation\Request $request): bool
    {
        // JSON compatibility.
        $body = Json::decode($request->getContent());
        return isset($body[$this->parameterName]);
    }

    public function onAuthenticationFailure(HttpFoundation\Request $request, AuthenticationException $exception): HttpFoundation\Response
    {
        return new HttpFoundation\JsonResponse(['error' => $exception->getMessage()], HttpFoundation\Response::HTTP_UNAUTHORIZED);
    }

    public function onAuthenticationSuccess(HttpFoundation\Request $request, TokenInterface $token, string $firewallName): ?HttpFoundation\Response
    {
        return $this->successHandler->onAuthenticationSuccess($request, $token);
    }
}
```
I hard-coded `$this->parameterName` by problems while dependency injection.

The class `App\Tools\Json` implement a simple JSON encoder/decore:
```php
/**
     * Decode Json string or throw error.
     *
     * @param string $json
     *
     * @return mixed
     *
     * @throws \Exception
     */
    public static function decode(string $json): mixed
    {
        $resp = json_decode($json, true);
        $lastJsonError = json_last_error_msg();
        if ('No error' !== $lastJsonError) {
            if (empty($json)) {
                $lastJsonError = 'The Json string is empty.';
            }
            throw new \Exception(self::t('Bad JSON format: @msg.', ['@msg' => $lastJsonError]));
        }

        return $resp;
    }
```

It's not the best code but works for now.

Now I can do this call in the Swagger UI:
```bash
curl -X 'POST' \
  'http://siasar3.localhost/api/v1/users/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "refresh_token": "4by44fe8i2nl999dflsz:mlfdkkhiok42yeunsd93lij32ibgx8xi"
}'
```
